INSERT INTO ROOM(ROOM_PRICE,ROOM_STATUS,ROOM_TYPE) VALUES(7000.00,'AVAILABLE','SINGLE');
INSERT INTO ROOM(ROOM_PRICE,ROOM_STATUS,ROOM_TYPE) VALUES(7000.00,'AVAILABLE','SINGLE');
INSERT INTO ROOM(ROOM_PRICE,ROOM_STATUS,ROOM_TYPE) VALUES(10000.00,'AVAILABLE','DOUBLE');
INSERT INTO ROOM(ROOM_PRICE,ROOM_STATUS,ROOM_TYPE) VALUES(10000.00,'AVAILABLE','DOUBLE');
INSERT INTO ROOM(ROOM_PRICE,ROOM_STATUS,ROOM_TYPE) VALUES(10000.00,'AVAILABLE','DOUBLE');

